spring.application.name=rewards
# Server configuration
server.port=8080

# Enable H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Ensure database initializes correctly
spring.sql.init.mode=always
spring.datasource.initialization-mode=always
spring.jpa.hibernate.ddl-auto=none  


